### ISSUE TITLE
Disable Video creation buttons untill requirements are done

### ISSUE THREAD

**Issue by Michel-NL** [SenorPez/project-cars-replay-enhancer-ui#12]
Just wanted this to be dummy proof ;-)

- If you create a new configuration and save it, you can push the video creation buttons. It will give you an error.
- If you create a new configuration and select a source video and save it, you can push the video creation buttons. It will give you an error.
- etc.

Maybe its better to disable the video creation buttons until all requirements are filled in?

**Comment by SenorPez** [comment]
Yeah, there's a couple of things I need to fix here.

1. I'm just going to have the configuration save if you click one of the video creation buttons. WAY TOO OFTEN in testing lately have I clicked the button, and realized I didn't save first.
2. I can disable them before your configuration is "complete." Interestingly enough, the only two fields you need for a configuration to be "complete" is `source_telemetry` and `output_video`. Everything else is optional.
3. (Probably a different change request, because it's surprisingly complicated to implement.) You should also be able to cancel the video creation. The same should go for the driver detection when you provide `source_telemetry`.
